---
title: "Intro2R"
subtitle: "Data Wrangling and Visualisation"
author: "xpsong"
institute: ""
date: "updated `r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: [default, metropolis, "custom-fonts.css"] #themes: names(xaringan:::list_css()) ("xaringan-themer.css" if you specify within .Rmd)
    lib_dir: libs
    nature:
      titleSlideClass: [center, middle, inverse, title-slide] #default
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

class: inverse, center, middle

# Outline  

__[blah](#4)__  

---

class: left

# Our Example Dataset  

__[Kaggle Machine Learning and Data Science Survey 2018](https://www.kaggle.com/kaggle/kaggle-survey-2018)__
- The industry-wide survey presents the state of data science and machine learning
- It was published in as raw a format as possible while ensuring the anonymity of respondents
- Our survey analysis has been adapted from R Notebooks published by the Kaggle users [Heads or Tails](https://www.kaggle.com/headsortails/what-we-do-in-the-kernels-a-kaggle-survey-story) and [Jose Berengueres](https://www.kaggle.com/harriken/storytelling-the-2018-kaggle-survey)


---

class: left

- Use `str()` to examine the data type for dataframe columns 

- Convert all multiple choice answers into factors using `mutate_if()`



- Use the pipe operator `%>%` to manipulate data in stages (from `dplyr` package)
  - It is a key operater often used in the `tidyverse`.
  - Rather than using nested brackets, the 'pipeline' is highly readable and follows a logical sequence.
  - For example:
```{r eval = FALSE}
round(exp(diff(log(x))), 1) #using nested brackets

x %>% log() %>% #using the pipe operator
    diff() %>%
    exp() %>%
    round(1)
```