---
title: "R Environment and Syntax"
subtitle: "Intro2R: Lesson 1 of 4"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
    theme: lumen
---

```{r load_packages, echo = FALSE, message = FALSE, warning = FALSE}
#to load packages can either use the command library() or require()

require(knitr) #to knit HMTL

require(dplyr) #data manipulation
require(tidyr) #data manipulation
require(ggplot2) #data visualisation

```



# Data cleaning

1) Save your .xlsx file as a csv (comma delimited) in the /raw folder and give it a name (eg. responses_YYYYMMDD.csv)

2) Load it into R

```{r message = FALSE, warning = FALSE}
#svy.df <- read.csv("raw/responses_20190311.csv", stringsAsFactors = FALSE, check.names=FALSE) 
#import the data as 'svy.df'
#the location of .Rproj file is where the working directory is (so, no need to type the entire file path)
```



```{r other tests, eval = FALSE}
#other tests u may consider

#require(stats)
t.test()


#other useful packages::functions to consider for surveys
library(survey)
svydesign() #specify survey design
survey::postStratify() #adjusts sampling weights so that the joint distribution of a set of post-stratifying variables matches the known population joint distribution. 

library(likert)

```


